name: 🙋‍♂️ [Web Serve] - Support & Feedback
description: "Get help with Web Serve, report bugs, or request features."
title: '🙋‍♂️ Support & Feedback: Web Serve'
labels: ['support', 'feedback', 'question']
body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="100" alt="Web Serve" src="https://github.com/user-attachments/assets/e1d9f76f-0f3d-4ba5-8a15-253ee173bb1c" /> **"Web Serve"** is a simple and easy-to-use application designed for quickly setting up and managing local static servers, suitable for a variety of use cases. 
        
        Whether you are a developer, designer, content creator, or a regular user, this application can bring you significant convenience and efficiency.

  - type: textarea
    attributes:
      label: 🙋‍♂️ How can we help you?
      description: Describe the issue you're facing or the feature you'd like to request.
      placeholder: For example, I'm experiencing an issue with...
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "💻 Desktop"
      description: Your operating system and version.
      options:
        - macOS 27.x (Golden Gate)
        - macOS 26.x (Tahoe)
        - macOS 15.x (Sequoia)
        - macOS 14.x (Sonoma)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **How can I send you a crash report for one of your apps?**

        - macOS Open Finder
        - Select Go to **Folder…** from the Go menu <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - Enter: **~/Library/Logs/DiagnosticReports**
        - In the resulting list, select all files that starts with the app name, ZIP them, and send me
        - Attach the file to this issue

  - type: textarea
    attributes:
      label: ℹ️ Additional context
      description: Add any additional information that could be helpful.
      placeholder: ex. Screenshots, steps to reproduce, etc.
    validations:
      required: false